# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import like_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_widget = QtWidgets.QWidget(self.centralwidget)
        self.up_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.up_widget.setStyleSheet("background-color: rgb(108, 108, 108);")
        self.up_widget.setObjectName("up_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.up_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(self.up_widget)
        self.Title.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.Title.setObjectName("Title")
        self.horizontalLayout_2.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.up_widget)
        self.down_widget = QtWidgets.QWidget(self.centralwidget)
        self.down_widget.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.down_widget.setObjectName("down_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.down_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.down_widget)
        self.menu.setStyleSheet("background-color: rgb(117, 117, 117);")
        self.menu.setObjectName("menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 300)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_button = QtWidgets.QPushButton(self.menu)
        self.search_button.setMaximumSize(QtCore.QSize(200, 50))
        self.search_button.setObjectName("search_button")
        self.verticalLayout_2.addWidget(self.search_button)
        self.like_button = QtWidgets.QPushButton(self.menu)
        self.like_button.setMaximumSize(QtCore.QSize(200, 50))
        self.like_button.setObjectName("like_button")
        self.verticalLayout_2.addWidget(self.like_button)
        self.comments_button = QtWidgets.QPushButton(self.menu)
        self.comments_button.setMaximumSize(QtCore.QSize(200, 50))
        self.comments_button.setObjectName("comments_button")
        self.verticalLayout_2.addWidget(self.comments_button)
        self.favourite_button = QtWidgets.QPushButton(self.menu)
        self.favourite_button.setMaximumSize(QtCore.QSize(200, 50))
        self.favourite_button.setObjectName("favourite_button")
        self.verticalLayout_2.addWidget(self.favourite_button)
        self.horizontalLayout.addWidget(self.menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.down_widget)
        self.stackedWidget.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.stackedWidget.addWidget(self.search_page)
        self.like_page = QtWidgets.QWidget()
        self.like_page.setObjectName("like_page")
        self.stackedWidget.addWidget(self.like_page)
        self.comments_page = QtWidgets.QWidget()
        self.comments_page.setObjectName("comments_page")
        self.stackedWidget.addWidget(self.comments_page)
        self.favourite_page = QtWidgets.QWidget()
        self.favourite_page.setObjectName("favourite_page")
        self.stackedWidget.addWidget(self.favourite_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.down_widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "MOVIE COMMENTS"))
        self.search_button.setText(_translate("MainWindow", "search"))
        self.like_button.setText(_translate("MainWindow", "like"))
        self.comments_button.setText(_translate("MainWindow", "comments"))
        self.favourite_button.setText(_translate("MainWindow", "favourite"))
