# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc
import random

class Ui_Form(QtWidgets.QWidget):
    def __init__(self, data):
        super(Ui_Form, self).__init__()
        self.setupUi(data)

    def setupUi(self, data):
        self.setObjectName("Form")
        self.resize(667, 522)

        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")

        self.movie_gridLayout = QtWidgets.QGridLayout()
        self.movie_gridLayout.setObjectName("movie_gridLayout")

        self.language = QtWidgets.QLabel(self)
        self.language.setObjectName("language")
        self.movie_gridLayout.addWidget(self.language, 0, 2, 1, 1)

        self.review_num = QtWidgets.QLabel(self)
        self.review_num.setObjectName("review_num")
        self.movie_gridLayout.addWidget(self.review_num, 1, 0, 1, 1)

        self.rate = QtWidgets.QLabel(self)
        self.rate.setObjectName("rate")
        self.movie_gridLayout.addWidget(self.rate, 1, 1, 1, 1)

        self.genre = QtWidgets.QLabel(self)
        self.genre.setObjectName("genre")
        self.movie_gridLayout.addWidget(self.genre, 0, 1, 1, 1)

        self.collect_widget = QtWidgets.QWidget(self)
        self.collect_widget.setObjectName("collect_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.collect_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)

        self.pushButton = QtWidgets.QToolButton(self.collect_widget)
        self.pushButton.setText("")
        self.pushButton.setCheckable(True)  # Make the button checkable
        self.pushButton.setChecked(True)  # Set the initial state
        self.checked_image = QtGui.QPixmap(":/icons/icons/favor_t.png")
        self.unchecked_image = QtGui.QPixmap(":/icons/icons/favor.png")
        self.pushButton.toggled.connect(self.onToggleButtonClicked)
        self.onToggleButtoninitialize()
        self.pushButton.setObjectName("pushButton")

        self.horizontalLayout_3.addWidget(self.pushButton)
        self.movie_gridLayout.addWidget(self.collect_widget, 1, 2, 1, 1)

        self.name_pushbutton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_pushbutton.sizePolicy().hasHeightForWidth())
        self.name_pushbutton.setSizePolicy(sizePolicy)
        self.name_pushbutton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.name_pushbutton.setStyleSheet("\n"
"#name_pushbutton{\n"
"text-align: left;\n"
"border:none;\n"
"padding-left: 20px; \n"
"}")
        self.name_pushbutton.setAutoDefault(False)
        self.name_pushbutton.setObjectName("name_pushbutton")
        self.movie_gridLayout.addWidget(self.name_pushbutton, 0, 0, 1, 1)

        self.verticalLayout_10.addLayout(self.movie_gridLayout)
        self.retranslateUi(data)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, data):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.language.setText(_translate("Form", str(data[3])))
        self.review_num.setText(_translate("Form", str(data[4])))
        self.rate.setText(_translate("Form", str(data[1])))
        self.genre.setText(_translate("Form", str(data[2])))
        self.name_pushbutton.setText(_translate("Form", str(data[0])))
    def onToggleButtoninitialize(self):
        icon = QtGui.QIcon()
        if self.pushButton.isChecked():
            icon.addPixmap(self.checked_image, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        else:
            icon.addPixmap(self.unchecked_image, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)

    def onToggleButtonClicked(self,state):
        icon = QtGui.QIcon()
        if state:
            icon.addPixmap(self.checked_image, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        else:
            icon.addPixmap(self.unchecked_image, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
# Example usage
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form(["Movie Name", "Rate", "Genre", "Language", "Review Number"])
    ui.show()
    sys.exit(app.exec_())
