# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_For(object):
    def setupUi(self, For):
        For.setObjectName("For")
        For.resize(667, 522)
        self.movie_widget = QtWidgets.QWidget(For)
        self.movie_widget.setGeometry(QtCore.QRect(50, 80, 381, 271))
        self.movie_widget.setObjectName("movie_widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.movie_widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.movie_gridLayout = QtWidgets.QGridLayout()
        self.movie_gridLayout.setObjectName("movie_gridLayout")
        self.language = QtWidgets.QLabel(self.movie_widget)
        self.language.setObjectName("language")
        self.movie_gridLayout.addWidget(self.language, 0, 2, 1, 1)
        self.review_num = QtWidgets.QLabel(self.movie_widget)
        self.review_num.setObjectName("review_num")
        self.movie_gridLayout.addWidget(self.review_num, 1, 0, 1, 1)
        self.rate = QtWidgets.QLabel(self.movie_widget)
        self.rate.setObjectName("rate")
        self.movie_gridLayout.addWidget(self.rate, 1, 1, 1, 1)
        self.genre = QtWidgets.QLabel(self.movie_widget)
        self.genre.setObjectName("genre")
        self.movie_gridLayout.addWidget(self.genre, 0, 1, 1, 1)
        self.collect_widget = QtWidgets.QWidget(self.movie_widget)
        self.collect_widget.setObjectName("collect_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.collect_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.collect_widget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/favor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.movie_gridLayout.addWidget(self.collect_widget, 1, 2, 1, 1)
        self.name_pushbutton = QtWidgets.QPushButton(self.movie_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_pushbutton.sizePolicy().hasHeightForWidth())
        self.name_pushbutton.setSizePolicy(sizePolicy)
        self.name_pushbutton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.name_pushbutton.setStyleSheet("\n"
"#name_pushbutton{\n"
"text-align: left;\n"
"border:nones;\n"
"padding-left: 20px; \n"
"}")
        self.name_pushbutton.setAutoDefault(False)
        self.name_pushbutton.setObjectName("name_pushbutton")
        self.movie_gridLayout.addWidget(self.name_pushbutton, 0, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.movie_gridLayout)

        self.retranslateUi(For)
        QtCore.QMetaObject.connectSlotsByName(For)

    def retranslateUi(self, For):
        _translate = QtCore.QCoreApplication.translate
        For.setWindowTitle(_translate("For", "Form"))
        self.language.setText(_translate("For", "language"))
        self.review_num.setText(_translate("For", "review_num"))
        self.rate.setText(_translate("For", "rate"))
        self.genre.setText(_translate("For", "genre"))
        self.name_pushbutton.setText(_translate("For", "name"))
import resource_rc
